// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureSession(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WirePath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SocketMode(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputSource {
    SystemDefault,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TranscriptionMode {
    BatchOnStop,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputTarget {
    SystemClipboard,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OutputTargets(Vec<OutputTarget>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WorkingSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WorkingSocketMode(SocketMode);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MetaSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MetaSocketMode(SocketMode);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureStoreDirectory(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ListenerDaemonConfiguration {
    pub working_socket_path: WorkingSocketPath,
    pub working_socket_mode: WorkingSocketMode,
    pub meta_socket_path: MetaSocketPath,
    pub meta_socket_mode: MetaSocketMode,
    pub capture_store_directory: CaptureStoreDirectory,
    pub input_source: InputSource,
    pub transcription_mode: TranscriptionMode,
    pub output_targets: OutputTargets,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StartCapture {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StopCapture(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StatusRequest {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StartedSession(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureStarted(StartedSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AudioArtifactPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DurableAudioArtifact(AudioArtifactPath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActiveCaptureSession(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActiveCapture {
    pub active_capture_session: ActiveCaptureSession,
    pub durable_audio_artifact: DurableAudioArtifact,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CaptureStatus {
    Idle,
    Capturing(ActiveCapture),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureStatusReport(CaptureStatus);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoppedSession(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TranscriptText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveredTo(OutputTarget);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DeliveryFailureReason {
    TargetUnavailable,
    TargetRejected,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryFailure {
    pub target: OutputTarget,
    pub reason: DeliveryFailureReason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeliveryOutcome {
    Delivered(DeliveredTo),
    Failed(DeliveryFailure),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryOutcomes(Vec<DeliveryOutcome>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureStopped {
    pub stopped_session: StoppedSession,
    pub durable_audio_artifact: DurableAudioArtifact,
    pub transcript_text: TranscriptText,
    pub delivery_outcomes: DeliveryOutcomes,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    Start,
    Stop,
    Status,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnimplementedReason {
    NotBuiltYet,
    AudioBackendUnavailable,
    TranscriptionBackendUnavailable,
    OutputTargetUnavailable,
    StoreUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnimplementedOperationKind(OperationKind);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Reason(UnimplementedReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented {
    pub unimplemented_operation_kind: UnimplementedOperationKind,
    pub reason: Reason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Start(StartCapture),
    Stop(StopCapture),
    Status(StatusRequest),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Started(CaptureStarted),
    Stopped(CaptureStopped),
    StatusReported(CaptureStatusReport),
    RequestUnimplemented(RequestUnimplemented),
}

#[rustfmt::skip]
impl CaptureSession {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CaptureSession {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WirePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WirePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SocketMode {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SocketMode {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OutputTargets {
    pub fn new(payload: Vec<OutputTarget>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<OutputTarget> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<OutputTarget> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<OutputTarget>> for OutputTargets {
    fn from(payload: Vec<OutputTarget>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WorkingSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for WorkingSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WorkingSocketMode {
    pub fn new(payload: SocketMode) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SocketMode {
        &self.0
    }
    pub fn into_payload(self) -> SocketMode {
        self.0
    }
}
#[rustfmt::skip]
impl From<SocketMode> for WorkingSocketMode {
    fn from(payload: SocketMode) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MetaSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for MetaSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MetaSocketMode {
    pub fn new(payload: SocketMode) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SocketMode {
        &self.0
    }
    pub fn into_payload(self) -> SocketMode {
        self.0
    }
}
#[rustfmt::skip]
impl From<SocketMode> for MetaSocketMode {
    fn from(payload: SocketMode) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureStoreDirectory {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for CaptureStoreDirectory {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StopCapture {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for StopCapture {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StartedSession {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for StartedSession {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureStarted {
    pub fn new(payload: StartedSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StartedSession {
        &self.0
    }
    pub fn into_payload(self) -> StartedSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<StartedSession> for CaptureStarted {
    fn from(payload: StartedSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AudioArtifactPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for AudioArtifactPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DurableAudioArtifact {
    pub fn new(payload: AudioArtifactPath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AudioArtifactPath {
        &self.0
    }
    pub fn into_payload(self) -> AudioArtifactPath {
        self.0
    }
}
#[rustfmt::skip]
impl From<AudioArtifactPath> for DurableAudioArtifact {
    fn from(payload: AudioArtifactPath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ActiveCaptureSession {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for ActiveCaptureSession {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureStatusReport {
    pub fn new(payload: CaptureStatus) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureStatus {
        &self.0
    }
    pub fn into_payload(self) -> CaptureStatus {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureStatus> for CaptureStatusReport {
    fn from(payload: CaptureStatus) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StoppedSession {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for StoppedSession {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TranscriptText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TranscriptText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliveredTo {
    pub fn new(payload: OutputTarget) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &OutputTarget {
        &self.0
    }
    pub fn into_payload(self) -> OutputTarget {
        self.0
    }
}
#[rustfmt::skip]
impl From<OutputTarget> for DeliveredTo {
    fn from(payload: OutputTarget) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliveryOutcomes {
    pub fn new(payload: Vec<DeliveryOutcome>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<DeliveryOutcome> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<DeliveryOutcome> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<DeliveryOutcome>> for DeliveryOutcomes {
    fn from(payload: Vec<DeliveryOutcome>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnimplementedOperationKind {
    pub fn new(payload: OperationKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &OperationKind {
        &self.0
    }
    pub fn into_payload(self) -> OperationKind {
        self.0
    }
}
#[rustfmt::skip]
impl From<OperationKind> for UnimplementedOperationKind {
    fn from(payload: OperationKind) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Reason {
    pub fn new(payload: UnimplementedReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UnimplementedReason {
        &self.0
    }
    pub fn into_payload(self) -> UnimplementedReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<UnimplementedReason> for Reason {
    fn from(payload: UnimplementedReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureStatus {
    pub fn capturing(payload: ActiveCapture) -> Self {
        Self::Capturing(payload)
    }
}

#[rustfmt::skip]
impl DeliveryOutcome {
    pub fn delivered(payload: OutputTarget) -> Self {
        Self::Delivered(DeliveredTo::new(payload))
    }
    pub fn failed(payload: DeliveryFailure) -> Self {
        Self::Failed(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn start(payload: StartCapture) -> Self {
        Self::Start(payload)
    }
    pub fn stop(payload: CaptureSession) -> Self {
        Self::Stop(StopCapture::new(payload))
    }
    pub fn status(payload: StatusRequest) -> Self {
        Self::Status(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn started(payload: StartedSession) -> Self {
        Self::Started(CaptureStarted::new(payload))
    }
    pub fn stopped(payload: CaptureStopped) -> Self {
        Self::Stopped(payload)
    }
    pub fn status_reported(payload: CaptureStatus) -> Self {
        Self::StatusReported(CaptureStatusReport::new(payload))
    }
    pub fn request_unimplemented(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<ActiveCapture> for CaptureStatus {
    fn from(payload: ActiveCapture) -> Self {
        Self::Capturing(payload)
    }
}

#[rustfmt::skip]
impl From<DeliveredTo> for DeliveryOutcome {
    fn from(payload: DeliveredTo) -> Self {
        Self::Delivered(payload)
    }
}

#[rustfmt::skip]
impl From<DeliveryFailure> for DeliveryOutcome {
    fn from(payload: DeliveryFailure) -> Self {
        Self::Failed(payload)
    }
}

#[rustfmt::skip]
impl From<StartCapture> for Input {
    fn from(payload: StartCapture) -> Self {
        Self::Start(payload)
    }
}

#[rustfmt::skip]
impl From<StopCapture> for Input {
    fn from(payload: StopCapture) -> Self {
        Self::Stop(payload)
    }
}

#[rustfmt::skip]
impl From<StatusRequest> for Input {
    fn from(payload: StatusRequest) -> Self {
        Self::Status(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureStarted> for Output {
    fn from(payload: CaptureStarted) -> Self {
        Self::Started(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureStopped> for Output {
    fn from(payload: CaptureStopped) -> Self {
        Self::Stopped(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureStatusReport> for Output {
    fn from(payload: CaptureStatusReport) -> Self {
        Self::StatusReported(payload)
    }
}

#[rustfmt::skip]
impl From<RequestUnimplemented> for Output {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_START: u64 = 0x0000000000000000;
    pub const INPUT_STOP: u64 = 0x0001000000000000;
    pub const INPUT_STATUS: u64 = 0x0002000000000000;
    pub const OUTPUT_STARTED: u64 = 0x0100000000000000;
    pub const OUTPUT_STOPPED: u64 = 0x0101000000000000;
    pub const OUTPUT_STATUS_REPORTED: u64 = 0x0102000000000000;
    pub const OUTPUT_REQUEST_UNIMPLEMENTED: u64 = 0x0103000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Start,
    Stop,
    Status,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Started,
    Stopped,
    StatusReported,
    RequestUnimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Start(_) => InputRoute::Start,
            Self::Stop(_) => InputRoute::Stop,
            Self::Status(_) => InputRoute::Status,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Start(_) => short_header::INPUT_START,
            Self::Stop(_) => short_header::INPUT_STOP,
            Self::Status(_) => short_header::INPUT_STATUS,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_START => Ok(InputRoute::Start),
            short_header::INPUT_STOP => Ok(InputRoute::Stop),
            short_header::INPUT_STATUS => Ok(InputRoute::Status),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Started(_) => OutputRoute::Started,
            Self::Stopped(_) => OutputRoute::Stopped,
            Self::StatusReported(_) => OutputRoute::StatusReported,
            Self::RequestUnimplemented(_) => OutputRoute::RequestUnimplemented,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Started(_) => short_header::OUTPUT_STARTED,
            Self::Stopped(_) => short_header::OUTPUT_STOPPED,
            Self::StatusReported(_) => short_header::OUTPUT_STATUS_REPORTED,
            Self::RequestUnimplemented(_) => short_header::OUTPUT_REQUEST_UNIMPLEMENTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_STARTED => Ok(OutputRoute::Started),
            short_header::OUTPUT_STOPPED => Ok(OutputRoute::Stopped),
            short_header::OUTPUT_STATUS_REPORTED => Ok(OutputRoute::StatusReported),
            short_header::OUTPUT_REQUEST_UNIMPLEMENTED => {
                Ok(OutputRoute::RequestUnimplemented)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &["Start", "Stop", "Status"];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
