// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureSession(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WirePath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SocketMode(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputSource {
    SystemDefault,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TranscriptionMode {
    BatchOnStop,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputTarget {
    SystemClipboard,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OutputTargets(Vec<OutputTarget>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WorkingSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WorkingSocketMode(SocketMode);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MetaSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MetaSocketMode(SocketMode);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureStoreDirectory(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ListenerDaemonConfiguration {
    pub working_socket_path: WorkingSocketPath,
    pub working_socket_mode: WorkingSocketMode,
    pub meta_socket_path: MetaSocketPath,
    pub meta_socket_mode: MetaSocketMode,
    pub capture_store_directory: CaptureStoreDirectory,
    pub input_source: InputSource,
    pub transcription_mode: TranscriptionMode,
    pub output_targets: OutputTargets,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StartCapture {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StopCapture(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CancelCapture(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StatusRequest {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ListCapturesRequest {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetryCapture(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ToggleCapture {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AcquireMaintenanceLease {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReleaseMaintenanceLease {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StartedSession(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureStarted(StartedSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AudioArtifactPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DurableAudioArtifact(AudioArtifactPath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActiveCaptureSession(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActiveCapture {
    pub active_capture_session: ActiveCaptureSession,
    pub durable_audio_artifact: DurableAudioArtifact,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CaptureStatus {
    Idle,
    Capturing(ActiveCapture),
    Finalizing(ActiveCapture),
    Transcribing(ActiveCapture),
    Delivered(CaptureSession),
    Error(CaptureSession),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureStatusReport(CaptureStatus);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum CaptureArtifactState {
    Recovering,
    Retryable,
    Completed,
    Failed,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureArtifactStateValue(CaptureArtifactState);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureArtifactBytes(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureArtifactDurationMilliseconds(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureSummary {
    pub capture_session: CaptureSession,
    pub capture_artifact_state_value: CaptureArtifactStateValue,
    pub durable_audio_artifact: DurableAudioArtifact,
    pub capture_artifact_bytes: CaptureArtifactBytes,
    pub capture_artifact_duration_milliseconds: CaptureArtifactDurationMilliseconds,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureSummaries(Vec<CaptureSummary>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureListReport(CaptureSummaries);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetriedSession(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureRetried {
    pub retried_session: RetriedSession,
    pub transcript_text: TranscriptText,
    pub delivery_outcomes: DeliveryOutcomes,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureAlreadyActive(ActiveCaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NoActiveCapture {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestedCaptureSession(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureSessionMismatch {
    pub active_capture_session: ActiveCaptureSession,
    pub requested_capture_session: RequestedCaptureSession,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoppedSession(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TranscriptText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveredTo(OutputTarget);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DeliveryFailureReason {
    TargetUnavailable,
    TargetRejected,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryFailure {
    pub output_target: OutputTarget,
    pub delivery_failure_reason: DeliveryFailureReason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeliveryOutcome {
    Delivered(DeliveredTo),
    Failed(DeliveryFailure),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryOutcomes(Vec<DeliveryOutcome>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureStopped {
    pub stopped_session: StoppedSession,
    pub durable_audio_artifact: DurableAudioArtifact,
    pub transcript_text: TranscriptText,
    pub delivery_outcomes: DeliveryOutcomes,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CancelledSession(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureCancelled {
    pub cancelled_session: CancelledSession,
    pub durable_audio_artifact: DurableAudioArtifact,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CancellationRequestedSession(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureCancellationRequested {
    pub cancellation_requested_session: CancellationRequestedSession,
    pub durable_audio_artifact: DurableAudioArtifact,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CompletionRequestedSession(CaptureSession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureCompletionRequested {
    pub completion_requested_session: CompletionRequestedSession,
    pub durable_audio_artifact: DurableAudioArtifact,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DaemonEpoch(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaintenanceLeaseEpoch(DaemonEpoch);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaintenanceLeaseGrant(MaintenanceLeaseEpoch);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaintenanceLeaseGranted(MaintenanceLeaseGrant);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaintenanceLeaseRelease {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaintenanceLeaseReleased(MaintenanceLeaseRelease);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaintenanceLeaseActiveState(MaintenanceLeaseEpoch);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaintenanceLeaseActive(MaintenanceLeaseActiveState);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaintenanceLeaseAbsent {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaintenanceLeaseNotHeld(MaintenanceLeaseAbsent);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaintenanceLeaseCancellation {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaintenanceLeaseCancelled(MaintenanceLeaseCancellation);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    Start,
    Stop,
    Cancel,
    Status,
    ListCaptures,
    Retry,
    Toggle,
    AcquireMaintenance,
    ReleaseMaintenance,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnimplementedReason {
    NotBuiltYet,
    AudioBackendUnavailable,
    TranscriptionBackendUnavailable,
    OutputTargetUnavailable,
    StoreUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnimplementedOperationKind(OperationKind);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Reason(UnimplementedReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented {
    pub unimplemented_operation_kind: UnimplementedOperationKind,
    pub reason: Reason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Start(StartCapture),
    Stop(StopCapture),
    Cancel(CancelCapture),
    Status(StatusRequest),
    ListCaptures(ListCapturesRequest),
    Retry(RetryCapture),
    Toggle(ToggleCapture),
    AcquireMaintenance(AcquireMaintenanceLease),
    ReleaseMaintenance(ReleaseMaintenanceLease),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Started(CaptureStarted),
    Stopped(CaptureStopped),
    Cancelled(CaptureCancelled),
    CancellationRequested(CaptureCancellationRequested),
    StatusReported(CaptureStatusReport),
    CapturesListed(CaptureListReport),
    Retried(CaptureRetried),
    AlreadyActive(CaptureAlreadyActive),
    NoActive(NoActiveCapture),
    SessionMismatch(CaptureSessionMismatch),
    Unimplemented(RequestUnimplemented),
    CompletionRequested(CaptureCompletionRequested),
    MaintenanceLeaseGranted(MaintenanceLeaseGrant),
    MaintenanceLeaseReleased(MaintenanceLeaseRelease),
    MaintenanceLeaseActive(MaintenanceLeaseActiveState),
    MaintenanceLeaseNotHeld(MaintenanceLeaseAbsent),
    MaintenanceLeaseCancelled(MaintenanceLeaseCancellation),
}

#[rustfmt::skip]
impl CaptureSession {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CaptureSession {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WirePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WirePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SocketMode {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SocketMode {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OutputTargets {
    pub fn new(payload: Vec<OutputTarget>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<OutputTarget> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<OutputTarget> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<OutputTarget>> for OutputTargets {
    fn from(payload: Vec<OutputTarget>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WorkingSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for WorkingSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WorkingSocketMode {
    pub fn new(payload: SocketMode) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SocketMode {
        &self.0
    }
    pub fn into_payload(self) -> SocketMode {
        self.0
    }
}
#[rustfmt::skip]
impl From<SocketMode> for WorkingSocketMode {
    fn from(payload: SocketMode) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MetaSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for MetaSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MetaSocketMode {
    pub fn new(payload: SocketMode) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SocketMode {
        &self.0
    }
    pub fn into_payload(self) -> SocketMode {
        self.0
    }
}
#[rustfmt::skip]
impl From<SocketMode> for MetaSocketMode {
    fn from(payload: SocketMode) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureStoreDirectory {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for CaptureStoreDirectory {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StopCapture {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for StopCapture {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CancelCapture {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for CancelCapture {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetryCapture {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for RetryCapture {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StartedSession {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for StartedSession {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureStarted {
    pub fn new(payload: StartedSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StartedSession {
        &self.0
    }
    pub fn into_payload(self) -> StartedSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<StartedSession> for CaptureStarted {
    fn from(payload: StartedSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AudioArtifactPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for AudioArtifactPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DurableAudioArtifact {
    pub fn new(payload: AudioArtifactPath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AudioArtifactPath {
        &self.0
    }
    pub fn into_payload(self) -> AudioArtifactPath {
        self.0
    }
}
#[rustfmt::skip]
impl From<AudioArtifactPath> for DurableAudioArtifact {
    fn from(payload: AudioArtifactPath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ActiveCaptureSession {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for ActiveCaptureSession {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureStatusReport {
    pub fn new(payload: CaptureStatus) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureStatus {
        &self.0
    }
    pub fn into_payload(self) -> CaptureStatus {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureStatus> for CaptureStatusReport {
    fn from(payload: CaptureStatus) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureArtifactStateValue {
    pub fn new(payload: CaptureArtifactState) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureArtifactState {
        &self.0
    }
    pub fn into_payload(self) -> CaptureArtifactState {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureArtifactState> for CaptureArtifactStateValue {
    fn from(payload: CaptureArtifactState) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureArtifactBytes {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CaptureArtifactBytes {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureArtifactDurationMilliseconds {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CaptureArtifactDurationMilliseconds {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureSummaries {
    pub fn new(payload: Vec<CaptureSummary>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<CaptureSummary> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<CaptureSummary> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<CaptureSummary>> for CaptureSummaries {
    fn from(payload: Vec<CaptureSummary>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureListReport {
    pub fn new(payload: CaptureSummaries) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSummaries {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSummaries {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSummaries> for CaptureListReport {
    fn from(payload: CaptureSummaries) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetriedSession {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for RetriedSession {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureAlreadyActive {
    pub fn new(payload: ActiveCaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ActiveCaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> ActiveCaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<ActiveCaptureSession> for CaptureAlreadyActive {
    fn from(payload: ActiveCaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RequestedCaptureSession {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for RequestedCaptureSession {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StoppedSession {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for StoppedSession {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TranscriptText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TranscriptText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliveredTo {
    pub fn new(payload: OutputTarget) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &OutputTarget {
        &self.0
    }
    pub fn into_payload(self) -> OutputTarget {
        self.0
    }
}
#[rustfmt::skip]
impl From<OutputTarget> for DeliveredTo {
    fn from(payload: OutputTarget) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliveryOutcomes {
    pub fn new(payload: Vec<DeliveryOutcome>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<DeliveryOutcome> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<DeliveryOutcome> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<DeliveryOutcome>> for DeliveryOutcomes {
    fn from(payload: Vec<DeliveryOutcome>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CancelledSession {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for CancelledSession {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CancellationRequestedSession {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for CancellationRequestedSession {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CompletionRequestedSession {
    pub fn new(payload: CaptureSession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CaptureSession {
        &self.0
    }
    pub fn into_payload(self) -> CaptureSession {
        self.0
    }
}
#[rustfmt::skip]
impl From<CaptureSession> for CompletionRequestedSession {
    fn from(payload: CaptureSession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DaemonEpoch {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for DaemonEpoch {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MaintenanceLeaseEpoch {
    pub fn new(payload: DaemonEpoch) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DaemonEpoch {
        &self.0
    }
    pub fn into_payload(self) -> DaemonEpoch {
        self.0
    }
}
#[rustfmt::skip]
impl From<DaemonEpoch> for MaintenanceLeaseEpoch {
    fn from(payload: DaemonEpoch) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MaintenanceLeaseGrant {
    pub fn new(payload: MaintenanceLeaseEpoch) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MaintenanceLeaseEpoch {
        &self.0
    }
    pub fn into_payload(self) -> MaintenanceLeaseEpoch {
        self.0
    }
}
#[rustfmt::skip]
impl From<MaintenanceLeaseEpoch> for MaintenanceLeaseGrant {
    fn from(payload: MaintenanceLeaseEpoch) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MaintenanceLeaseGranted {
    pub fn new(payload: MaintenanceLeaseGrant) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MaintenanceLeaseGrant {
        &self.0
    }
    pub fn into_payload(self) -> MaintenanceLeaseGrant {
        self.0
    }
}
#[rustfmt::skip]
impl From<MaintenanceLeaseGrant> for MaintenanceLeaseGranted {
    fn from(payload: MaintenanceLeaseGrant) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MaintenanceLeaseReleased {
    pub fn new(payload: MaintenanceLeaseRelease) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MaintenanceLeaseRelease {
        &self.0
    }
    pub fn into_payload(self) -> MaintenanceLeaseRelease {
        self.0
    }
}
#[rustfmt::skip]
impl From<MaintenanceLeaseRelease> for MaintenanceLeaseReleased {
    fn from(payload: MaintenanceLeaseRelease) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MaintenanceLeaseActiveState {
    pub fn new(payload: MaintenanceLeaseEpoch) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MaintenanceLeaseEpoch {
        &self.0
    }
    pub fn into_payload(self) -> MaintenanceLeaseEpoch {
        self.0
    }
}
#[rustfmt::skip]
impl From<MaintenanceLeaseEpoch> for MaintenanceLeaseActiveState {
    fn from(payload: MaintenanceLeaseEpoch) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MaintenanceLeaseActive {
    pub fn new(payload: MaintenanceLeaseActiveState) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MaintenanceLeaseActiveState {
        &self.0
    }
    pub fn into_payload(self) -> MaintenanceLeaseActiveState {
        self.0
    }
}
#[rustfmt::skip]
impl From<MaintenanceLeaseActiveState> for MaintenanceLeaseActive {
    fn from(payload: MaintenanceLeaseActiveState) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MaintenanceLeaseNotHeld {
    pub fn new(payload: MaintenanceLeaseAbsent) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MaintenanceLeaseAbsent {
        &self.0
    }
    pub fn into_payload(self) -> MaintenanceLeaseAbsent {
        self.0
    }
}
#[rustfmt::skip]
impl From<MaintenanceLeaseAbsent> for MaintenanceLeaseNotHeld {
    fn from(payload: MaintenanceLeaseAbsent) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MaintenanceLeaseCancelled {
    pub fn new(payload: MaintenanceLeaseCancellation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MaintenanceLeaseCancellation {
        &self.0
    }
    pub fn into_payload(self) -> MaintenanceLeaseCancellation {
        self.0
    }
}
#[rustfmt::skip]
impl From<MaintenanceLeaseCancellation> for MaintenanceLeaseCancelled {
    fn from(payload: MaintenanceLeaseCancellation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnimplementedOperationKind {
    pub fn new(payload: OperationKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &OperationKind {
        &self.0
    }
    pub fn into_payload(self) -> OperationKind {
        self.0
    }
}
#[rustfmt::skip]
impl From<OperationKind> for UnimplementedOperationKind {
    fn from(payload: OperationKind) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Reason {
    pub fn new(payload: UnimplementedReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UnimplementedReason {
        &self.0
    }
    pub fn into_payload(self) -> UnimplementedReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<UnimplementedReason> for Reason {
    fn from(payload: UnimplementedReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureStatus {
    pub fn capturing(payload: ActiveCapture) -> Self {
        Self::Capturing(payload)
    }
    pub fn finalizing(payload: ActiveCapture) -> Self {
        Self::Finalizing(payload)
    }
    pub fn transcribing(payload: ActiveCapture) -> Self {
        Self::Transcribing(payload)
    }
    pub fn delivered(payload: Integer) -> Self {
        Self::Delivered(CaptureSession::new(payload))
    }
    pub fn error(payload: Integer) -> Self {
        Self::Error(CaptureSession::new(payload))
    }
}

#[rustfmt::skip]
impl DeliveryOutcome {
    pub fn delivered(payload: OutputTarget) -> Self {
        Self::Delivered(DeliveredTo::new(payload))
    }
    pub fn failed(payload: DeliveryFailure) -> Self {
        Self::Failed(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn start(payload: StartCapture) -> Self {
        Self::Start(payload)
    }
    pub fn stop(payload: CaptureSession) -> Self {
        Self::Stop(StopCapture::new(payload))
    }
    pub fn cancel(payload: CaptureSession) -> Self {
        Self::Cancel(CancelCapture::new(payload))
    }
    pub fn status(payload: StatusRequest) -> Self {
        Self::Status(payload)
    }
    pub fn list_captures(payload: ListCapturesRequest) -> Self {
        Self::ListCaptures(payload)
    }
    pub fn retry(payload: CaptureSession) -> Self {
        Self::Retry(RetryCapture::new(payload))
    }
    pub fn toggle(payload: ToggleCapture) -> Self {
        Self::Toggle(payload)
    }
    pub fn acquire_maintenance(payload: AcquireMaintenanceLease) -> Self {
        Self::AcquireMaintenance(payload)
    }
    pub fn release_maintenance(payload: ReleaseMaintenanceLease) -> Self {
        Self::ReleaseMaintenance(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn started(payload: StartedSession) -> Self {
        Self::Started(CaptureStarted::new(payload))
    }
    pub fn stopped(payload: CaptureStopped) -> Self {
        Self::Stopped(payload)
    }
    pub fn cancelled(payload: CaptureCancelled) -> Self {
        Self::Cancelled(payload)
    }
    pub fn cancellation_requested(payload: CaptureCancellationRequested) -> Self {
        Self::CancellationRequested(payload)
    }
    pub fn status_reported(payload: CaptureStatus) -> Self {
        Self::StatusReported(CaptureStatusReport::new(payload))
    }
    pub fn captures_listed(payload: CaptureSummaries) -> Self {
        Self::CapturesListed(CaptureListReport::new(payload))
    }
    pub fn retried(payload: CaptureRetried) -> Self {
        Self::Retried(payload)
    }
    pub fn already_active(payload: ActiveCaptureSession) -> Self {
        Self::AlreadyActive(CaptureAlreadyActive::new(payload))
    }
    pub fn no_active(payload: NoActiveCapture) -> Self {
        Self::NoActive(payload)
    }
    pub fn session_mismatch(payload: CaptureSessionMismatch) -> Self {
        Self::SessionMismatch(payload)
    }
    pub fn unimplemented(payload: RequestUnimplemented) -> Self {
        Self::Unimplemented(payload)
    }
    pub fn completion_requested(payload: CaptureCompletionRequested) -> Self {
        Self::CompletionRequested(payload)
    }
    pub fn maintenance_lease_granted(payload: MaintenanceLeaseEpoch) -> Self {
        Self::MaintenanceLeaseGranted(MaintenanceLeaseGrant::new(payload))
    }
    pub fn maintenance_lease_released(payload: MaintenanceLeaseRelease) -> Self {
        Self::MaintenanceLeaseReleased(payload)
    }
    pub fn maintenance_lease_active(payload: MaintenanceLeaseEpoch) -> Self {
        Self::MaintenanceLeaseActive(MaintenanceLeaseActiveState::new(payload))
    }
    pub fn maintenance_lease_not_held(payload: MaintenanceLeaseAbsent) -> Self {
        Self::MaintenanceLeaseNotHeld(payload)
    }
    pub fn maintenance_lease_cancelled(payload: MaintenanceLeaseCancellation) -> Self {
        Self::MaintenanceLeaseCancelled(payload)
    }
}

#[rustfmt::skip]
impl From<DeliveredTo> for DeliveryOutcome {
    fn from(payload: DeliveredTo) -> Self {
        Self::Delivered(payload)
    }
}

#[rustfmt::skip]
impl From<DeliveryFailure> for DeliveryOutcome {
    fn from(payload: DeliveryFailure) -> Self {
        Self::Failed(payload)
    }
}

#[rustfmt::skip]
impl From<StartCapture> for Input {
    fn from(payload: StartCapture) -> Self {
        Self::Start(payload)
    }
}

#[rustfmt::skip]
impl From<StopCapture> for Input {
    fn from(payload: StopCapture) -> Self {
        Self::Stop(payload)
    }
}

#[rustfmt::skip]
impl From<CancelCapture> for Input {
    fn from(payload: CancelCapture) -> Self {
        Self::Cancel(payload)
    }
}

#[rustfmt::skip]
impl From<StatusRequest> for Input {
    fn from(payload: StatusRequest) -> Self {
        Self::Status(payload)
    }
}

#[rustfmt::skip]
impl From<ListCapturesRequest> for Input {
    fn from(payload: ListCapturesRequest) -> Self {
        Self::ListCaptures(payload)
    }
}

#[rustfmt::skip]
impl From<RetryCapture> for Input {
    fn from(payload: RetryCapture) -> Self {
        Self::Retry(payload)
    }
}

#[rustfmt::skip]
impl From<ToggleCapture> for Input {
    fn from(payload: ToggleCapture) -> Self {
        Self::Toggle(payload)
    }
}

#[rustfmt::skip]
impl From<AcquireMaintenanceLease> for Input {
    fn from(payload: AcquireMaintenanceLease) -> Self {
        Self::AcquireMaintenance(payload)
    }
}

#[rustfmt::skip]
impl From<ReleaseMaintenanceLease> for Input {
    fn from(payload: ReleaseMaintenanceLease) -> Self {
        Self::ReleaseMaintenance(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureStarted> for Output {
    fn from(payload: CaptureStarted) -> Self {
        Self::Started(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureStopped> for Output {
    fn from(payload: CaptureStopped) -> Self {
        Self::Stopped(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureCancelled> for Output {
    fn from(payload: CaptureCancelled) -> Self {
        Self::Cancelled(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureCancellationRequested> for Output {
    fn from(payload: CaptureCancellationRequested) -> Self {
        Self::CancellationRequested(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureStatusReport> for Output {
    fn from(payload: CaptureStatusReport) -> Self {
        Self::StatusReported(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureListReport> for Output {
    fn from(payload: CaptureListReport) -> Self {
        Self::CapturesListed(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureRetried> for Output {
    fn from(payload: CaptureRetried) -> Self {
        Self::Retried(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureAlreadyActive> for Output {
    fn from(payload: CaptureAlreadyActive) -> Self {
        Self::AlreadyActive(payload)
    }
}

#[rustfmt::skip]
impl From<NoActiveCapture> for Output {
    fn from(payload: NoActiveCapture) -> Self {
        Self::NoActive(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureSessionMismatch> for Output {
    fn from(payload: CaptureSessionMismatch) -> Self {
        Self::SessionMismatch(payload)
    }
}

#[rustfmt::skip]
impl From<RequestUnimplemented> for Output {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::Unimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureCompletionRequested> for Output {
    fn from(payload: CaptureCompletionRequested) -> Self {
        Self::CompletionRequested(payload)
    }
}

#[rustfmt::skip]
impl From<MaintenanceLeaseGrant> for Output {
    fn from(payload: MaintenanceLeaseGrant) -> Self {
        Self::MaintenanceLeaseGranted(payload)
    }
}

#[rustfmt::skip]
impl From<MaintenanceLeaseRelease> for Output {
    fn from(payload: MaintenanceLeaseRelease) -> Self {
        Self::MaintenanceLeaseReleased(payload)
    }
}

#[rustfmt::skip]
impl From<MaintenanceLeaseActiveState> for Output {
    fn from(payload: MaintenanceLeaseActiveState) -> Self {
        Self::MaintenanceLeaseActive(payload)
    }
}

#[rustfmt::skip]
impl From<MaintenanceLeaseAbsent> for Output {
    fn from(payload: MaintenanceLeaseAbsent) -> Self {
        Self::MaintenanceLeaseNotHeld(payload)
    }
}

#[rustfmt::skip]
impl From<MaintenanceLeaseCancellation> for Output {
    fn from(payload: MaintenanceLeaseCancellation) -> Self {
        Self::MaintenanceLeaseCancelled(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_START: u64 = 0x0000000000000000;
    pub const INPUT_STOP: u64 = 0x0001000000000000;
    pub const INPUT_CANCEL: u64 = 0x0002000000000000;
    pub const INPUT_STATUS: u64 = 0x0003000000000000;
    pub const INPUT_LIST_CAPTURES: u64 = 0x0004000000000000;
    pub const INPUT_RETRY: u64 = 0x0005000000000000;
    pub const INPUT_TOGGLE: u64 = 0x0006000000000000;
    pub const INPUT_ACQUIRE_MAINTENANCE: u64 = 0x0007000000000000;
    pub const INPUT_RELEASE_MAINTENANCE: u64 = 0x0008000000000000;
    pub const OUTPUT_STARTED: u64 = 0x0100000000000000;
    pub const OUTPUT_STOPPED: u64 = 0x0101000000000000;
    pub const OUTPUT_CANCELLED: u64 = 0x0102000000000000;
    pub const OUTPUT_CANCELLATION_REQUESTED: u64 = 0x0103000000000000;
    pub const OUTPUT_STATUS_REPORTED: u64 = 0x0104000000000000;
    pub const OUTPUT_CAPTURES_LISTED: u64 = 0x0105000000000000;
    pub const OUTPUT_RETRIED: u64 = 0x0106000000000000;
    pub const OUTPUT_ALREADY_ACTIVE: u64 = 0x0107000000000000;
    pub const OUTPUT_NO_ACTIVE: u64 = 0x0108000000000000;
    pub const OUTPUT_SESSION_MISMATCH: u64 = 0x0109000000000000;
    pub const OUTPUT_UNIMPLEMENTED: u64 = 0x010A000000000000;
    pub const OUTPUT_COMPLETION_REQUESTED: u64 = 0x010B000000000000;
    pub const OUTPUT_MAINTENANCE_LEASE_GRANTED: u64 = 0x010C000000000000;
    pub const OUTPUT_MAINTENANCE_LEASE_RELEASED: u64 = 0x010D000000000000;
    pub const OUTPUT_MAINTENANCE_LEASE_ACTIVE: u64 = 0x010E000000000000;
    pub const OUTPUT_MAINTENANCE_LEASE_NOT_HELD: u64 = 0x010F000000000000;
    pub const OUTPUT_MAINTENANCE_LEASE_CANCELLED: u64 = 0x0110000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
/// Reserved refusal header. Real variant headers pack root and
/// variant indices into the top sixteen bits and leave the low
/// forty-eight bits zero, so the all-ones value can never name a
/// declared variant.
const ENGINE_REFUSAL_SHORT_HEADER: u64 = u64::MAX;
#[rustfmt::skip]
/// Why the daemon refused to produce an ordinary reply.
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq
)]
pub enum EngineRefusalReason {
    /// The engine ran and rejected the request with its typed
    /// domain error; the rendered error text is the detail.
    Rejected,
    /// The engine layer could not serve the request at all.
    Unavailable,
}
#[rustfmt::skip]
impl std::fmt::Display for EngineRefusalReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rejected => formatter.write_str("engine rejected the request"),
            Self::Unavailable => formatter.write_str("engine unavailable"),
        }
    }
}
#[rustfmt::skip]
/// The refusal reply a daemon writes when the engine failed, so
/// the caller receives a complete typed frame instead of a closed
/// socket it cannot distinguish from daemon death. The typed
/// engine error stays daemon-side; the wire carries the
/// classification plus the rendered error text.
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineRefusal {
    pub reason: EngineRefusalReason,
    pub detail: String,
}
#[rustfmt::skip]
impl EngineRefusal {
    pub fn rejected(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Rejected,
            detail,
        }
    }
    pub fn unavailable(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Unavailable,
            detail,
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&ENGINE_REFUSAL_SHORT_HEADER.to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
    EngineRefused { refusal: EngineRefusal },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
            Self::EngineRefused { refusal } => {
                write!(formatter, "{}: {}", refusal.reason, refusal.detail)
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Start,
    Stop,
    Cancel,
    Status,
    ListCaptures,
    Retry,
    Toggle,
    AcquireMaintenance,
    ReleaseMaintenance,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Started,
    Stopped,
    Cancelled,
    CancellationRequested,
    StatusReported,
    CapturesListed,
    Retried,
    AlreadyActive,
    NoActive,
    SessionMismatch,
    Unimplemented,
    CompletionRequested,
    MaintenanceLeaseGranted,
    MaintenanceLeaseReleased,
    MaintenanceLeaseActive,
    MaintenanceLeaseNotHeld,
    MaintenanceLeaseCancelled,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Start(_) => InputRoute::Start,
            Self::Stop(_) => InputRoute::Stop,
            Self::Cancel(_) => InputRoute::Cancel,
            Self::Status(_) => InputRoute::Status,
            Self::ListCaptures(_) => InputRoute::ListCaptures,
            Self::Retry(_) => InputRoute::Retry,
            Self::Toggle(_) => InputRoute::Toggle,
            Self::AcquireMaintenance(_) => InputRoute::AcquireMaintenance,
            Self::ReleaseMaintenance(_) => InputRoute::ReleaseMaintenance,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Start(_) => short_header::INPUT_START,
            Self::Stop(_) => short_header::INPUT_STOP,
            Self::Cancel(_) => short_header::INPUT_CANCEL,
            Self::Status(_) => short_header::INPUT_STATUS,
            Self::ListCaptures(_) => short_header::INPUT_LIST_CAPTURES,
            Self::Retry(_) => short_header::INPUT_RETRY,
            Self::Toggle(_) => short_header::INPUT_TOGGLE,
            Self::AcquireMaintenance(_) => short_header::INPUT_ACQUIRE_MAINTENANCE,
            Self::ReleaseMaintenance(_) => short_header::INPUT_RELEASE_MAINTENANCE,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_START => Ok(InputRoute::Start),
            short_header::INPUT_STOP => Ok(InputRoute::Stop),
            short_header::INPUT_CANCEL => Ok(InputRoute::Cancel),
            short_header::INPUT_STATUS => Ok(InputRoute::Status),
            short_header::INPUT_LIST_CAPTURES => Ok(InputRoute::ListCaptures),
            short_header::INPUT_RETRY => Ok(InputRoute::Retry),
            short_header::INPUT_TOGGLE => Ok(InputRoute::Toggle),
            short_header::INPUT_ACQUIRE_MAINTENANCE => Ok(InputRoute::AcquireMaintenance),
            short_header::INPUT_RELEASE_MAINTENANCE => Ok(InputRoute::ReleaseMaintenance),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        if header == ENGINE_REFUSAL_SHORT_HEADER {
            let refusal = rkyv::from_bytes::<
                EngineRefusal,
                rkyv::rancor::Error,
            >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
                .map_err(|_| SignalFrameError::ArchiveDecode)?;
            return Err(SignalFrameError::EngineRefused {
                refusal,
            });
        }
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Started(_) => OutputRoute::Started,
            Self::Stopped(_) => OutputRoute::Stopped,
            Self::Cancelled(_) => OutputRoute::Cancelled,
            Self::CancellationRequested(_) => OutputRoute::CancellationRequested,
            Self::StatusReported(_) => OutputRoute::StatusReported,
            Self::CapturesListed(_) => OutputRoute::CapturesListed,
            Self::Retried(_) => OutputRoute::Retried,
            Self::AlreadyActive(_) => OutputRoute::AlreadyActive,
            Self::NoActive(_) => OutputRoute::NoActive,
            Self::SessionMismatch(_) => OutputRoute::SessionMismatch,
            Self::Unimplemented(_) => OutputRoute::Unimplemented,
            Self::CompletionRequested(_) => OutputRoute::CompletionRequested,
            Self::MaintenanceLeaseGranted(_) => OutputRoute::MaintenanceLeaseGranted,
            Self::MaintenanceLeaseReleased(_) => OutputRoute::MaintenanceLeaseReleased,
            Self::MaintenanceLeaseActive(_) => OutputRoute::MaintenanceLeaseActive,
            Self::MaintenanceLeaseNotHeld(_) => OutputRoute::MaintenanceLeaseNotHeld,
            Self::MaintenanceLeaseCancelled(_) => OutputRoute::MaintenanceLeaseCancelled,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Started(_) => short_header::OUTPUT_STARTED,
            Self::Stopped(_) => short_header::OUTPUT_STOPPED,
            Self::Cancelled(_) => short_header::OUTPUT_CANCELLED,
            Self::CancellationRequested(_) => short_header::OUTPUT_CANCELLATION_REQUESTED,
            Self::StatusReported(_) => short_header::OUTPUT_STATUS_REPORTED,
            Self::CapturesListed(_) => short_header::OUTPUT_CAPTURES_LISTED,
            Self::Retried(_) => short_header::OUTPUT_RETRIED,
            Self::AlreadyActive(_) => short_header::OUTPUT_ALREADY_ACTIVE,
            Self::NoActive(_) => short_header::OUTPUT_NO_ACTIVE,
            Self::SessionMismatch(_) => short_header::OUTPUT_SESSION_MISMATCH,
            Self::Unimplemented(_) => short_header::OUTPUT_UNIMPLEMENTED,
            Self::CompletionRequested(_) => short_header::OUTPUT_COMPLETION_REQUESTED,
            Self::MaintenanceLeaseGranted(_) => {
                short_header::OUTPUT_MAINTENANCE_LEASE_GRANTED
            }
            Self::MaintenanceLeaseReleased(_) => {
                short_header::OUTPUT_MAINTENANCE_LEASE_RELEASED
            }
            Self::MaintenanceLeaseActive(_) => {
                short_header::OUTPUT_MAINTENANCE_LEASE_ACTIVE
            }
            Self::MaintenanceLeaseNotHeld(_) => {
                short_header::OUTPUT_MAINTENANCE_LEASE_NOT_HELD
            }
            Self::MaintenanceLeaseCancelled(_) => {
                short_header::OUTPUT_MAINTENANCE_LEASE_CANCELLED
            }
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_STARTED => Ok(OutputRoute::Started),
            short_header::OUTPUT_STOPPED => Ok(OutputRoute::Stopped),
            short_header::OUTPUT_CANCELLED => Ok(OutputRoute::Cancelled),
            short_header::OUTPUT_CANCELLATION_REQUESTED => {
                Ok(OutputRoute::CancellationRequested)
            }
            short_header::OUTPUT_STATUS_REPORTED => Ok(OutputRoute::StatusReported),
            short_header::OUTPUT_CAPTURES_LISTED => Ok(OutputRoute::CapturesListed),
            short_header::OUTPUT_RETRIED => Ok(OutputRoute::Retried),
            short_header::OUTPUT_ALREADY_ACTIVE => Ok(OutputRoute::AlreadyActive),
            short_header::OUTPUT_NO_ACTIVE => Ok(OutputRoute::NoActive),
            short_header::OUTPUT_SESSION_MISMATCH => Ok(OutputRoute::SessionMismatch),
            short_header::OUTPUT_UNIMPLEMENTED => Ok(OutputRoute::Unimplemented),
            short_header::OUTPUT_COMPLETION_REQUESTED => {
                Ok(OutputRoute::CompletionRequested)
            }
            short_header::OUTPUT_MAINTENANCE_LEASE_GRANTED => {
                Ok(OutputRoute::MaintenanceLeaseGranted)
            }
            short_header::OUTPUT_MAINTENANCE_LEASE_RELEASED => {
                Ok(OutputRoute::MaintenanceLeaseReleased)
            }
            short_header::OUTPUT_MAINTENANCE_LEASE_ACTIVE => {
                Ok(OutputRoute::MaintenanceLeaseActive)
            }
            short_header::OUTPUT_MAINTENANCE_LEASE_NOT_HELD => {
                Ok(OutputRoute::MaintenanceLeaseNotHeld)
            }
            short_header::OUTPUT_MAINTENANCE_LEASE_CANCELLED => {
                Ok(OutputRoute::MaintenanceLeaseCancelled)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        if header == ENGINE_REFUSAL_SHORT_HEADER {
            let refusal = rkyv::from_bytes::<
                EngineRefusal,
                rkyv::rancor::Error,
            >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
                .map_err(|_| SignalFrameError::ArchiveDecode)?;
            return Err(SignalFrameError::EngineRefused {
                refusal,
            });
        }
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Start",
        "Stop",
        "Cancel",
        "Status",
        "ListCaptures",
        "Retry",
        "Toggle",
        "AcquireMaintenance",
        "ReleaseMaintenance",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
